substitutions:
  name: aquapi
  friendly_name: AquaPi
packages:
  twinsen68.aquapigpt : github://Twinsen68/aquamonitgpt/config.yaml@main
esphome:
  # Version minimale requise pour ESPHome
  min_version: 2024.6.0  # Assurez-vous que cette version d'ESPHome est installée
  name: "${name}"  # Nom unique de l'appareil dans le réseau (défini dans substitutions.yaml)
  friendly_name: "${friendly_name}"  # Nom lisible dans l'interface utilisateur (HA)
  name_add_mac_suffix: true  # Ajoute un suffixe MAC au nom pour éviter les conflits réseau
  project:
    name: twinsen68.aquapigpt  # Identifiant unique du projet pour référence
    version: "2.0.0"  # Version actuelle du projet
  platform: esp32  # Spécifie la plateforme matérielle utilisée
  board: esp32dev  # Spécifie la carte ESP32 exacte utilisée

api:
  encryption:
    key: tBHSAVjYJjdf5o9Q4po3p/0U6YppKXuMnIdaUpjNkmY=

ota:
  safe_mode: true  # Mode sécurisé pour éviter les corruptions
  reboot_timeout: 5min  # Redémarrage automatique après une tentative échouée

dashboard_import:
  package_import_url: github://Twinsen68/aquamonitgpt/aquapi_config.yaml@main
  import_full_config: ${import_config}
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
