esphome:
  min_version: 2024.6.0
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: twinsen68.aquapigpt
    version: "2.0.0"
  platform: esp32
  board: esp32dev

packages:
  twinsen68.aquapigpt : github://Twinsen68/aquamonitgpt/config.yaml@main

api:
  encryption:
    key: tBHSAVjYJjdf5o9Q4po3p/0U6YppKXuMnIdaUpjNkmY=

ota:
  - platform: http_request

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
